"""add ti_paid_amount

Revision ID: 0b6314aa28d8
Revises: 839db6a0582f
Create Date: 2025-08-17 09:06:35.026437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b6314aa28d8'
down_revision = '839db6a0582f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_income', schema='assets') as batch_op:
        batch_op.add_column(sa.Column('ti_paid_amount', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_income', schema='assets') as batch_op:
        batch_op.drop_column('ti_paid_amount')

    # ### end Alembic commands ###
