"""add finance models

Revision ID: 0be17a04b590
Revises: abf481a4ccf8
Create Date: 2025-04-09 11:55:47.112803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0be17a04b590'
down_revision = 'abf481a4ccf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('c_created_by', sa.String(), nullable=False),
    sa.Column('c_created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('c_organization_id', sa.String(), nullable=False),
    sa.Column('c_name', sa.String(length=100), nullable=False),
    sa.Column('c_email', sa.String(length=120), nullable=False),
    sa.Column('c_phone', sa.String(length=100), nullable=True),
    sa.Column('c_to_email', sa.String(length=100), nullable=True),
    sa.Column('c_emailed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['c_created_by'], ['users.users.id'], ),
    sa.ForeignKeyConstraint(['c_organization_id'], ['users.organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('c_email'),
    schema='assets'
    )
    op.create_table('trip_expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('te_created_by', sa.String(), nullable=False),
    sa.Column('te_created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('te_organization_id', sa.String(), nullable=False),
    sa.Column('te_trip_id', sa.Integer(), nullable=True),
    sa.Column('te_asset_id', sa.Integer(), nullable=True),
    sa.Column('te_operator_id', sa.Integer(), nullable=True),
    sa.Column('te_status', sa.String(), nullable=False),
    sa.Column('te_type', sa.String(), nullable=True),
    sa.Column('te_amount', sa.Float(), nullable=False),
    sa.Column('te_description', sa.String(length=200), nullable=True),
    sa.Column('te_receipt_image', sa.String(length=200), nullable=True),
    sa.Column('te_receipt_pdf', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['te_asset_id'], ['assets.assets.id'], ),
    sa.ForeignKeyConstraint(['te_created_by'], ['users.users.id'], ),
    sa.ForeignKeyConstraint(['te_operator_id'], ['assets.operators.id'], ),
    sa.ForeignKeyConstraint(['te_organization_id'], ['users.organization.id'], ),
    sa.ForeignKeyConstraint(['te_trip_id'], ['assets.trips.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='assets'
    )
    op.create_table('trip_income',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ti_created_by', sa.String(), nullable=False),
    sa.Column('ti_created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ti_organization_id', sa.String(), nullable=False),
    sa.Column('ti_paid_at', sa.DateTime(), nullable=True),
    sa.Column('ti_trip_id', sa.Integer(), nullable=True),
    sa.Column('ti_asset_id', sa.Integer(), nullable=True),
    sa.Column('ti_operator_id', sa.Integer(), nullable=True),
    sa.Column('ti_client_id', sa.Integer(), nullable=True),
    sa.Column('ti_status', sa.String(), nullable=False),
    sa.Column('ti_type', sa.String(), nullable=True),
    sa.Column('ti_amount', sa.Float(), nullable=False),
    sa.Column('ti_description', sa.String(length=200), nullable=True),
    sa.Column('ti_receipt_image', sa.String(length=200), nullable=True),
    sa.Column('ti_receipt_pdf', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['ti_asset_id'], ['assets.assets.id'], ),
    sa.ForeignKeyConstraint(['ti_client_id'], ['assets.clients.id'], ),
    sa.ForeignKeyConstraint(['ti_created_by'], ['users.users.id'], ),
    sa.ForeignKeyConstraint(['ti_operator_id'], ['assets.operators.id'], ),
    sa.ForeignKeyConstraint(['ti_organization_id'], ['users.organization.id'], ),
    sa.ForeignKeyConstraint(['ti_trip_id'], ['assets.trips.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='assets'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trip_income', schema='assets')
    op.drop_table('trip_expense', schema='assets')
    op.drop_table('clients', schema='assets')
    # ### end Alembic commands ###
