"""empty message

Revision ID: 20b9398c6d8e
Revises: d17b3acaff29
Create Date: 2025-07-26 11:27:03.670579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20b9398c6d8e'
down_revision = 'd17b3acaff29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operators', schema='assets') as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operators', schema='assets') as batch_op:
        batch_op.drop_column('deleted')

    # ### end Alembic commands ###
