"""adjust card model1

Revision ID: 2644b8de13af
Revises: 69405cf41ede
Create Date: 2024-07-28 10:24:04.865934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2644b8de13af'
down_revision = '69405cf41ede'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fuel_request', schema='assets')
    op.drop_table('cards', schema='assets')
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('c_created_by', sa.String(), nullable=False),
    sa.Column('c_created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('c_organization_id', sa.String(), nullable=False),
    sa.Column('c_assign_by', sa.String(), nullable=True),
    sa.Column('c_assigned_at', sa.DateTime(), nullable=True),
    sa.Column('c_assigned_to', sa.Integer(), nullable=True),
    sa.Column('c_attached_asset', sa.Integer(), nullable=True),
    sa.Column('c_number', sa.String(), nullable=False),
    sa.Column('c_expiry_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['c_assign_by'], ['users.users.id'], ),
    sa.ForeignKeyConstraint(['c_assigned_to'], ['assets.operators.id'], ),
    sa.ForeignKeyConstraint(['c_attached_asset'], ['assets.assets.id'], ),
    sa.ForeignKeyConstraint(['c_created_by'], ['users.users.id'], ),
    sa.ForeignKeyConstraint(['c_organization_id'], ['users.organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='assets'
    )
    op.create_table('fuel_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('f_created_by', sa.String(), nullable=False),
    sa.Column('f_created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('f_organization_id', sa.String(), nullable=False),
    sa.Column('f_operator_id', sa.Integer(), nullable=False),
    sa.Column('f_asset_id', sa.Integer(), nullable=True),
    sa.Column('f_trip_id', sa.Integer(), nullable=True),
    sa.Column('f_card_id', sa.Integer(), nullable=True),
    sa.Column('f_status', sa.String(), nullable=False),
    sa.Column('f_type', sa.String(), nullable=True),
    sa.Column('f_litres', sa.Float(), nullable=False),
    sa.Column('f_cost', sa.Float(), nullable=True),
    sa.Column('f_total_cost', sa.Float(), nullable=False),
    sa.Column('f_distance', sa.Float(), nullable=True),
    sa.Column('f_vendor', sa.String(), nullable=True),
    sa.Column('f_odometer_image', sa.String(length=200), nullable=True),
    sa.Column('f_odometer_reading', sa.Float(), nullable=True),
    sa.Column('f_receipt_image', sa.String(length=200), nullable=True),
    sa.Column('f_receipt_pdf', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['f_asset_id'], ['assets.assets.id'], ),
    sa.ForeignKeyConstraint(['f_card_id'], ['assets.cards.id'], ),
    sa.ForeignKeyConstraint(['f_created_by'], ['users.users.id'], ),
    sa.ForeignKeyConstraint(['f_operator_id'], ['assets.operators.id'], ),
    sa.ForeignKeyConstraint(['f_organization_id'], ['users.organization.id'], ),
    sa.ForeignKeyConstraint(['f_trip_id'], ['assets.trips.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='assets'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fuel_request', schema='assets')
    op.drop_table('cards', schema='assets')

    # ### end Alembic commands ###
