"""modify trip

Revision ID: 2863468f1124
Revises: a6d85bee0095
Create Date: 2025-03-10 01:00:52.341868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2863468f1124'
down_revision = 'a6d85bee0095'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema='assets') as batch_op:
        batch_op.add_column(sa.Column('t_start_od_reading', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('t_start_od_reading_url', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('t_end_od_reading', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('t_end_od_reading_url', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema='assets') as batch_op:
        batch_op.drop_column('t_end_od_reading_url')
        batch_op.drop_column('t_end_od_reading')
        batch_op.drop_column('t_start_od_reading_url')
        batch_op.drop_column('t_start_od_reading')

    # ### end Alembic commands ###
