"""adjust organization and user id

Revision ID: 2b615a2bc62b
Revises: f793d8b3f3b4
Create Date: 2024-07-16 11:20:24.495517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b615a2bc62b'
down_revision = 'f793d8b3f3b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP TABLE users.organization CASCADE')
    op.create_table('organization',
    sa.Column('id', sa.String(), nullable=True),
    sa.Column('default_id', sa.Integer(), nullable=False),
    sa.Column('f_name', sa.String(length=80), nullable=False),
    sa.Column('f_industry', sa.String(length=80), nullable=False),
    sa.Column('f_country', sa.String(length=80), nullable=False),
    sa.Column('f_email', sa.String(length=120), nullable=False),
    sa.Column('f_size', sa.Integer(), nullable=False),
    sa.Column('f_fiscal_start', sa.Date(), nullable=True),
    sa.Column('f_fiscal_stop', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('default_id'),
    sa.UniqueConstraint('f_country'),
    sa.UniqueConstraint('f_email'),
    sa.UniqueConstraint('f_industry'),
    sa.UniqueConstraint('f_name'),
    sa.UniqueConstraint('id'),
    schema='users'
    )
    op.execute('DROP TABLE users.users CASCADE')
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=True),
    sa.Column('default_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('Organization_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('default_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('username'),
    schema='users'
    )
   ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users', schema='users')
    op.drop_table('organization', schema='users')
    # ### end Alembic commands ###
