"""adjust user class

Revision ID: 412022a0546f
Revises: ac34c940cc0d
Create Date: 2024-07-16 22:25:26.043441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '412022a0546f'
down_revision = 'ac34c940cc0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users', schema='users')  
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=True),
    sa.Column('default_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('Organization_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('default_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('username'),
    schema='users'
    )
 # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('users', schema='users')
    # ### end Alembic commands ###
