"""initial migration

Revision ID: 46f9a234ac02
Revises: 
Create Date: 2025-02-20 01:00:47.417857

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '46f9a234ac02'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ostatus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('o_name', sa.String(length=200), nullable=True),
    sa.Column('o_name_code', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='assets'
    )
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('s_name', sa.String(length=200), nullable=True),
    sa.Column('s_name_code', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='assets'
    )
    op.create_table('tstatus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('t_name', sa.String(length=200), nullable=True),
    sa.Column('t_name_code', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='assets'
    )
    op.create_table('organization',
    sa.Column('id', sa.String(), nullable=True),
    sa.Column('default_id', sa.Integer(), nullable=False),
    sa.Column('org_name', sa.String(length=80), nullable=False),
    sa.Column('org_industry', sa.String(length=80), nullable=True),
    sa.Column('org_country', sa.String(length=80), nullable=True),
    sa.Column('org_email', sa.String(length=120), nullable=True),
    sa.Column('org_size', sa.Integer(), nullable=True),
    sa.Column('org_fiscal_start', sa.Date(), nullable=True),
    sa.Column('org_fiscal_stop', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('default_id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('org_name'),
    schema='users'
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=True),
    sa.Column('default_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('default_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('username'),
    schema='users'
    )
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('a_organisation_id', sa.String(), nullable=False),
    sa.Column('a_created_by', sa.String(), nullable=False),
    sa.Column('a_created_at', sa.DateTime(), nullable=False),
    sa.Column('a_name', sa.String(length=100), nullable=False),
    sa.Column('a_make', sa.String(length=100), nullable=False),
    sa.Column('a_model', sa.String(length=100), nullable=False),
    sa.Column('a_year', sa.Integer(), nullable=False),
    sa.Column('a_license_plate', sa.String(length=50), nullable=False),
    sa.Column('a_type', sa.String(length=50), nullable=True),
    sa.Column('a_msrp', sa.Float(), nullable=True),
    sa.Column('a_chasis_no', sa.String(length=100), nullable=True),
    sa.Column('a_engine_size', sa.Float(), nullable=False),
    sa.Column('a_tank_size', sa.Float(), nullable=False),
    sa.Column('a_efficiency_rate', sa.Float(), nullable=False),
    sa.Column('a_fuel_type', sa.String(length=50), nullable=False),
    sa.Column('a_cost', sa.Float(), nullable=False),
    sa.Column('a_value', sa.Float(), nullable=False),
    sa.Column('a_depreciation_rate', sa.Float(), nullable=False),
    sa.Column('a_apreciation_rate', sa.Float(), nullable=False),
    sa.Column('a_accumulated_dep', sa.Float(), nullable=True),
    sa.Column('a_image', sa.String(length=200), nullable=True),
    sa.Column('a_attachment1', sa.String(length=200), nullable=True),
    sa.Column('a_attachment2', sa.String(length=200), nullable=True),
    sa.Column('a_attachment3', sa.String(length=200), nullable=True),
    sa.Column('a_status', sa.String(length=50), nullable=False),
    sa.Column('a_displacement', sa.Float(), nullable=True),
    sa.Column('a_mileage', sa.Float(), nullable=True),
    sa.Column('a_horsepower', sa.Float(), nullable=True),
    sa.Column('a_acceleration', sa.Float(), nullable=True),
    sa.Column('a_insurance_expiry', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['a_created_by'], ['users.users.id'], ),
    sa.ForeignKeyConstraint(['a_organisation_id'], ['users.organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='assets'
    )
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('c_created_by', sa.String(), nullable=False),
    sa.Column('c_created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('c_organization_id', sa.String(), nullable=False),
    sa.Column('c_assigned_at', sa.DateTime(), nullable=True),
    sa.Column('c_number', sa.String(), nullable=False),
    sa.Column('c_expiry_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['c_created_by'], ['users.users.id'], ),
    sa.ForeignKeyConstraint(['c_organization_id'], ['users.organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='assets'
    )
    op.create_table('operators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('o_organisation_id', sa.String(), nullable=False),
    sa.Column('o_created_by', sa.String(), nullable=False),
    sa.Column('o_created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('o_name', sa.String(length=100), nullable=False),
    sa.Column('o_email', sa.String(length=120), nullable=False),
    sa.Column('o_phone', sa.String(length=100), nullable=True),
    sa.Column('o_national_id', sa.String(length=100), nullable=True),
    sa.Column('o_lincense_id', sa.String(length=100), nullable=True),
    sa.Column('o_lincense_type', sa.String(length=100), nullable=True),
    sa.Column('o_lincense_expiry', sa.DateTime(), nullable=True),
    sa.Column('o_assigned_asset', sa.Integer(), nullable=True),
    sa.Column('o_payment_card_id', sa.Integer(), nullable=True),
    sa.Column('o_Payment_card_no', sa.String(length=100), nullable=True),
    sa.Column('o_role', sa.String(length=100), nullable=True),
    sa.Column('o_image', sa.String(length=200), nullable=True),
    sa.Column('o_status', sa.String(length=100), nullable=False),
    sa.Column('o_cum_mileage', sa.Numeric(), nullable=True),
    sa.Column('o_expirence', sa.Numeric(), nullable=True),
    sa.Column('o_attachment1', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['o_assigned_asset'], ['assets.assets.id'], ),
    sa.ForeignKeyConstraint(['o_created_by'], ['users.users.id'], ),
    sa.ForeignKeyConstraint(['o_organisation_id'], ['users.organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('o_email'),
    schema='assets'
    )
    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('t_origin_place_id', sa.String(length=255), nullable=True),
    sa.Column('t_origin_place_query', sa.String(length=255), nullable=True),
    sa.Column('t_destination_place_id', sa.String(length=255), nullable=True),
    sa.Column('t_destination_place_query', sa.String(length=255), nullable=True),
    sa.Column('t_distance', sa.String(length=50), nullable=True),
    sa.Column('t_duration', sa.String(length=50), nullable=True),
    sa.Column('t_directionsResponse', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('t_created_by', sa.String(), nullable=False),
    sa.Column('t_created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('t_organization_id', sa.String(), nullable=False),
    sa.Column('t_type', sa.String(length=100), nullable=True),
    sa.Column('t_start_lat', sa.Numeric(), nullable=True),
    sa.Column('t_start_long', sa.Numeric(), nullable=True),
    sa.Column('t_start_elavation', sa.Numeric(), nullable=True),
    sa.Column('t_end_lat', sa.Numeric(), nullable=True),
    sa.Column('t_end_long', sa.Numeric(), nullable=True),
    sa.Column('t_end_elavation', sa.Numeric(), nullable=True),
    sa.Column('t_start_date', sa.DateTime(), nullable=True),
    sa.Column('t_end_date', sa.DateTime(), nullable=True),
    sa.Column('t_operator_id', sa.Integer(), nullable=True),
    sa.Column('t_asset_id', sa.Integer(), nullable=True),
    sa.Column('t_status', sa.String(), nullable=False),
    sa.Column('t_load', sa.Float(), nullable=True),
    sa.Column('t_est_fuel', sa.Float(), nullable=True),
    sa.Column('t_actual_fuel', sa.Float(), nullable=True),
    sa.Column('t_est_cost', sa.Float(), nullable=True),
    sa.Column('t_actual_cost', sa.Float(), nullable=True),
    sa.Column('t_consumption_variance', sa.Float(), nullable=True),
    sa.Column('t_cost_variance', sa.Float(), nullable=True),
    sa.Column('t_odometer_reading1', sa.Float(), nullable=True),
    sa.Column('t_dometer_reading2', sa.Float(), nullable=True),
    sa.Column('t_dometer_reading3', sa.Float(), nullable=True),
    sa.Column('t_dometer_reading4', sa.Float(), nullable=True),
    sa.Column('t_dometer_reading5', sa.Float(), nullable=True),
    sa.Column('t_odometer_image1', sa.String(length=200), nullable=True),
    sa.Column('t_odometer_image2', sa.String(length=200), nullable=True),
    sa.Column('t_odometer_image3', sa.String(length=200), nullable=True),
    sa.Column('t_odometer_image4', sa.String(length=200), nullable=True),
    sa.Column('t_odometer_image5', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['t_asset_id'], ['assets.assets.id'], ),
    sa.ForeignKeyConstraint(['t_created_by'], ['users.users.id'], ),
    sa.ForeignKeyConstraint(['t_operator_id'], ['assets.operators.id'], ),
    sa.ForeignKeyConstraint(['t_organization_id'], ['users.organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='assets'
    )
    op.create_table('fuel_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('f_created_by', sa.String(), nullable=False),
    sa.Column('f_created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('f_organization_id', sa.String(), nullable=False),
    sa.Column('f_operator_id', sa.Integer(), nullable=False),
    sa.Column('f_asset_id', sa.Integer(), nullable=True),
    sa.Column('f_trip_id', sa.Integer(), nullable=True),
    sa.Column('f_card_id', sa.Integer(), nullable=True),
    sa.Column('f_status', sa.String(), nullable=False),
    sa.Column('f_type', sa.String(), nullable=True),
    sa.Column('f_litres', sa.Float(), nullable=False),
    sa.Column('f_cost', sa.Float(), nullable=True),
    sa.Column('f_total_cost', sa.Float(), nullable=False),
    sa.Column('f_distance', sa.Float(), nullable=True),
    sa.Column('f_vendor', sa.String(), nullable=True),
    sa.Column('f_odometer_image', sa.String(length=200), nullable=True),
    sa.Column('f_odometer_reading', sa.Float(), nullable=True),
    sa.Column('f_receipt_image', sa.String(length=200), nullable=True),
    sa.Column('f_receipt_pdf', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['f_asset_id'], ['assets.assets.id'], ),
    sa.ForeignKeyConstraint(['f_card_id'], ['assets.cards.id'], ),
    sa.ForeignKeyConstraint(['f_created_by'], ['users.users.id'], ),
    sa.ForeignKeyConstraint(['f_operator_id'], ['assets.operators.id'], ),
    sa.ForeignKeyConstraint(['f_organization_id'], ['users.organization.id'], ),
    sa.ForeignKeyConstraint(['f_trip_id'], ['assets.trips.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='assets'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fuel_request', schema='assets')
    op.drop_table('trips', schema='assets')
    op.drop_table('operators', schema='assets')
    op.drop_table('cards', schema='assets')
    op.drop_table('assets', schema='assets')
    op.drop_table('users', schema='users')
    op.drop_table('organization', schema='users')
    op.drop_table('tstatus', schema='assets')
    op.drop_table('status', schema='assets')
    op.drop_table('ostatus', schema='assets')
    # ### end Alembic commands ###
