"""empty message

Revision ID: 4f649d01ccd9
Revises: 20b9398c6d8e
Create Date: 2025-08-03 13:50:47.547017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f649d01ccd9'
down_revision = '20b9398c6d8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema='assets') as batch_op:
        batch_op.add_column(sa.Column('c_paid_amount', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema='assets') as batch_op:
        batch_op.drop_column('c_paid_amount')

    # ### end Alembic commands ###
