"""add maintanance model

Revision ID: 53fca111f941
Revises: aac657822c5b
Create Date: 2025-05-31 18:23:38.123859

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "53fca111f941"
down_revision = "aac657822c5b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "maintenance",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "m_created", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("m_created_by", sa.String(), nullable=False),
        sa.Column("m_asset_id", sa.Integer(), nullable=False),
        sa.Column("m_type", sa.String(), nullable=False),
        sa.Column("m_description", sa.String(), nullable=True),
        sa.Column("m_date", sa.Date(), nullable=True),
        sa.Column("m_total_cost", sa.Float(), nullable=True),
        sa.Column("m_insurance_coverage", sa.String(), nullable=True),
        sa.Column("m_status", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["m_asset_id"],
            ["assets.assets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="assets",
    )
    with op.batch_alter_table("users", schema="users") as batch_op:
        batch_op.create_foreign_key(
            None, "users", ["created_by"], ["id"], referent_schema="users"
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema="users") as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")

    op.drop_table("maintenance", schema="assets")
    # ### end Alembic commands ###
