"""add trips model

Revision ID: 548f6f2d8ece
Revises: e0d65b2b7835
Create Date: 2024-07-16 09:43:25.658873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '548f6f2d8ece'
down_revision = 'e0d65b2b7835'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('operators', schema='assets', cascade=True)
    op.execute('DROP TABLE assets.operators CASCADE')
    op.create_table('operators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('o_name', sa.String(length=100), nullable=False),
    sa.Column('o_email', sa.String(length=120), nullable=False),
    sa.Column('o_phone', sa.String(length=100), nullable=True),
    sa.Column('o_national_id', sa.String(length=100), nullable=True),
    sa.Column('o_lincense_id', sa.String(length=100), nullable=True),
    sa.Column('o_lincense_type', sa.String(length=100), nullable=True),
    sa.Column('o_lincense_expiry', sa.DateTime(), nullable=True),
    sa.Column('o_assigned_asset', sa.Integer(), nullable=True),
    sa.Column('o_payment_card_id', sa.Integer(), nullable=True),
    sa.Column('o_Payment_card_no', sa.String(length=100), nullable=True),
    sa.Column('o_role', sa.String(length=100), nullable=True),
    sa.Column('o_image', sa.String(length=200), nullable=True),
    sa.Column('o_status', sa.String(length=100), nullable=False),
    sa.Column('o_cum_mileage', sa.Numeric(), nullable=True),
    sa.Column('o_expirence', sa.Numeric(), nullable=True),
    sa.Column('o_attachment1', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['o_assigned_asset'], ['assets.assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('o_email'),
    schema='assets'
    )
    op.drop_table('trips', schema='assets')
    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('t_firm_id', sa.Integer(), nullable=False),
    sa.Column('t_type', sa.String(length=100), nullable=False),
    sa.Column('t_start_lat', sa.Numeric(), nullable=False),
    sa.Column('t_start_long', sa.Numeric(), nullable=False),
    sa.Column('t_start_elavation', sa.Numeric(), nullable=False),
    sa.Column('t_end_lat', sa.Numeric(), nullable=False),
    sa.Column('t_end_long', sa.Numeric(), nullable=False),
    sa.Column('t_end_elavation', sa.Numeric(), nullable=False),
    sa.Column('t_distance', sa.Float(), nullable=True),
    sa.Column('t_start_date', sa.DateTime(), nullable=True),
    sa.Column('t_end_date', sa.DateTime(), nullable=True),
    sa.Column('t_operator_id', sa.Integer(), nullable=True),
    sa.Column('t_asset_id', sa.Integer(), nullable=True),
    sa.Column('t_status', sa.String(), nullable=False),
    sa.Column('t_load', sa.Float(), nullable=True),
    sa.Column('t_est_fuel', sa.Float(), nullable=True),
    sa.Column('t_actual_fuel', sa.Float(), nullable=True),
    sa.Column('t_est_cost', sa.Float(), nullable=True),
    sa.Column('t_actual_cost', sa.Float(), nullable=True),
    sa.Column('t_consumption_variance', sa.Float(), nullable=True),
    sa.Column('t_cost_variance', sa.Float(), nullable=True),
    sa.Column('t_odometer_reading1', sa.Float(), nullable=True),
    sa.Column('t_dometer_reading2', sa.Float(), nullable=True),
    sa.Column('t_dometer_reading3', sa.Float(), nullable=True),
    sa.Column('t_dometer_reading4', sa.Float(), nullable=True),
    sa.Column('t_dometer_reading5', sa.Float(), nullable=True),
    sa.Column('t_odometer_image1', sa.String(length=200), nullable=True),
    sa.Column('t_odometer_image2', sa.String(length=200), nullable=True),
    sa.Column('t_odometer_image3', sa.String(length=200), nullable=True),
    sa.Column('t_odometer_image4', sa.String(length=200), nullable=True),
    sa.Column('t_odometer_image5', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['t_asset_id'], ['assets.assets.id'], ),
    sa.ForeignKeyConstraint(['t_firm_id'], ['users.firm.id'], ),
    sa.ForeignKeyConstraint(['t_operator_id'], ['assets.operators.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='assets'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trips', schema='assets')
    op.drop_table('operators', schema='assets')
    # ### end Alembic commands ###
