"""modify odometer readings

Revision ID: 605275c00fa4
Revises: 8b32cbee2e27
Create Date: 2025-03-07 17:04:08.220326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '605275c00fa4'
down_revision = '8b32cbee2e27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('odometer_readings', schema='assets') as batch_op:
        batch_op.add_column(sa.Column('or_created_by', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('or_organization_id', sa.String(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['or_created_by'], ['id'], referent_schema='users')
        batch_op.create_foreign_key(None, 'organization', ['or_organization_id'], ['id'], referent_schema='users')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('odometer_readings', schema='assets') as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('or_organization_id')
        batch_op.drop_column('or_created_by')

    # ### end Alembic commands ###
