"""adjust notification model

Revision ID: 60acb31a1b9f
Revises: f808ae0bee65
Create Date: 2025-09-08 13:25:46.261037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60acb31a1b9f'
down_revision = 'f808ae0bee65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema='users') as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('to_be_emailed', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('to_be_smsed', sa.Boolean(), nullable=False))
        batch_op.create_foreign_key(None, 'organization', ['organization_id'], ['id'], referent_schema='users')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema='users') as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('to_be_smsed')
        batch_op.drop_column('to_be_emailed')
        batch_op.drop_column('organization_id')

    # ### end Alembic commands ###
