"""Initial migration.

Revision ID: 725bec6b6ea6
Revises: 
Create Date: 2024-07-07 15:49:38.769711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '725bec6b6ea6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    schema='users'
    )
    op.create_table('asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('a_name', sa.String(length=100), nullable=False),
    sa.Column('a_make', sa.String(length=100), nullable=False),
    sa.Column('a_model', sa.String(length=100), nullable=False),
    sa.Column('a_year', sa.Integer(), nullable=False),
    sa.Column('a_license_plate', sa.String(length=50), nullable=False),
    sa.Column('a_type', sa.String(length=50), nullable=False),
    sa.Column('a_msrp', sa.Float(), nullable=False),
    sa.Column('a_chasis_no', sa.String(length=100), nullable=False),
    sa.Column('a_engine_size', sa.Float(), nullable=False),
    sa.Column('a_tank_size', sa.Float(), nullable=False),
    sa.Column('a_efficiency_rate', sa.Float(), nullable=False),
    sa.Column('a_fuel_type', sa.String(length=50), nullable=False),
    sa.Column('a_cost', sa.Float(), nullable=False),
    sa.Column('a_value', sa.Float(), nullable=False),
    sa.Column('a_depreciation_rate', sa.Float(), nullable=False),
    sa.Column('a_apreciation_rate', sa.Float(), nullable=False),
    sa.Column('a_accumulated_dep', sa.Float(), nullable=False),
    sa.Column('a_image', sa.String(length=200), nullable=True),
    sa.Column('a_attachment1', sa.String(length=200), nullable=True),
    sa.Column('a_attachment2', sa.String(length=200), nullable=True),
    sa.Column('a_attachment3', sa.String(length=200), nullable=True),
    sa.Column('a_status', sa.String(length=50), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='assets'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asset', schema='assets')
    op.drop_table('user', schema='users')
    # ### end Alembic commands ###
