"""add stops

Revision ID: 7a47bcf951f3
Revises: db315bf3f59b
Create Date: 2025-09-16 00:07:50.476430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a47bcf951f3'
down_revision = 'db315bf3f59b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['users.permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['users.roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['users.roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('stops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('s_trip_id', sa.Integer(), nullable=False),
    sa.Column('s_client_id', sa.Integer(), nullable=True),
    sa.Column('s_place_id', sa.String(length=255), nullable=True),
    sa.Column('s_place_query', sa.String(length=255), nullable=True),
    sa.Column('s_lat', sa.Numeric(), nullable=True),
    sa.Column('s_long', sa.Numeric(), nullable=True),
    sa.Column('s_sequence', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['s_client_id'], ['assets.clients.id'], ),
    sa.ForeignKeyConstraint(['s_trip_id'], ['assets.trips.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='assets'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stops', schema='assets')
    op.drop_table('user_roles')
    op.drop_table('role_permissions')
    # ### end Alembic commands ###
