"""update fuel_request

Revision ID: 808d4962c84f
Revises: ef4b371f8de9
Create Date: 2025-02-25 23:53:03.879045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '808d4962c84f'
down_revision = 'ef4b371f8de9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuel_request', schema='assets') as batch_op:
        batch_op.add_column(sa.Column('f_request_type', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuel_request', schema='assets') as batch_op:
        batch_op.drop_column('f_request_type')

    # ### end Alembic commands ###
