"""adjust notification org field

Revision ID: 818143f13d7e
Revises: 60acb31a1b9f
Create Date: 2025-09-08 13:40:54.010849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '818143f13d7e'
down_revision = '60acb31a1b9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema='users') as batch_op:
        batch_op.add_column(sa.Column('organisation_id', sa.String(), nullable=True))
        batch_op.drop_constraint('notifications_organization_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'organization', ['organisation_id'], ['id'], referent_schema='users')
        batch_op.drop_column('organization_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema='users') as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('notifications_organization_id_fkey', 'organization', ['organization_id'], ['id'], referent_schema='users')
        batch_op.drop_column('organisation_id')

    # ### end Alembic commands ###
