"""edit f_estimated_litres

Revision ID: 839db6a0582f
Revises: bea110179248
Create Date: 2025-08-12 16:51:57.822674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '839db6a0582f'
down_revision = 'bea110179248'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuel_request', schema='assets') as batch_op:
        batch_op.alter_column('f_litres',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('f_total_cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuel_request', schema='assets') as batch_op:
        batch_op.alter_column('f_total_cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('f_litres',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)

    # ### end Alembic commands ###
