"""add odometer readings

Revision ID: 8b32cbee2e27
Revises: ca92a29b8d0f
Create Date: 2025-03-07 16:49:33.139976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b32cbee2e27'
down_revision = 'ca92a29b8d0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('odometer_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('or_created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('or_trip_id', sa.Integer(), nullable=True),
    sa.Column('or_asset_id', sa.Integer(), nullable=True),
    sa.Column('or_operator_id', sa.Integer(), nullable=True),
    sa.Column('or_image', sa.String(length=200), nullable=True),
    sa.Column('or_by_drivers', sa.Boolean(), nullable=False),
    sa.Column('or_reading', sa.Float(), nullable=False),
    sa.Column('or_latitude', sa.Float(), nullable=True),
    sa.Column('or_longitude', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['or_asset_id'], ['assets.assets.id'], ),
    sa.ForeignKeyConstraint(['or_operator_id'], ['assets.operators.id'], ),
    sa.ForeignKeyConstraint(['or_trip_id'], ['assets.trips.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='assets'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('odometer_readings', schema='assets')
    # ### end Alembic commands ###
