"""adjust t_type in trips

Revision ID: 8c1a4e9b5dfc
Revises: c0b693a38e81
Create Date: 2024-07-18 01:22:53.524532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c1a4e9b5dfc'
down_revision = 'c0b693a38e81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema='assets') as batch_op:
        batch_op.alter_column('t_type',
                              existing_type=sa.String(),
                              nullable=True)
 # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trips', schema='assets')
    # ### end Alembic commands ###
