"""add columns

Revision ID: 92d80725cb2f
Revises: 53fca111f941
Create Date: 2025-06-12 21:01:24.817314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92d80725cb2f'
down_revision = '53fca111f941'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance', schema='assets') as batch_op:
        batch_op.add_column(sa.Column('m_organisation_id', sa.String(), nullable=True))
        batch_op.create_foreign_key(None, 'organization', ['m_organisation_id'], ['id'], referent_schema='users')

    with op.batch_alter_table('trips', schema='assets') as batch_op:
        batch_op.add_column(sa.Column('t_client_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'clients', ['t_client_id'], ['id'], referent_schema='assets')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema='assets') as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('t_client_id')

    with op.batch_alter_table('maintenance', schema='assets') as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('m_organisation_id')

    # ### end Alembic commands ###
