"""add-googleresponse-columns

Revision ID: a0e85bca724d
Revises: 2644b8de13af
Create Date: 2024-09-04 00:03:12.303251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0e85bca724d'
down_revision = '2644b8de13af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('t_origin_place_id', sa.String(length=255), nullable=True), schema='assets')
    op.add_column('trips', sa.Column('t_origin_place_query', sa.String(length=255), nullable=True), schema='assets')
    op.add_column('trips', sa.Column('t_destination_place_id', sa.String(length=255), nullable=True), schema='assets')
    op.add_column('trips', sa.Column('t_destination_place_query', sa.String(length=255), nullable=True), schema='assets')
    op.add_column('trips', sa.Column('t_distance', sa.String(length=100), nullable=True), schema='assets')
    op.add_column('trips', sa.Column('t_duration', sa.String(length=100), nullable=True), schema='assets')
    op.add_column('trips', sa.Column('t_directionsResponse', sa.JSON(), nullable=True), schema='assets')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove the columns from the trips table
    op.drop_column('trips', 't_origin_place_id', schema='assets')
    op.drop_column('trips', 't_origin_place_query', schema='assets')
    op.drop_column('trips', 't_destination_place_id', schema='assets')
    op.drop_column('trips', 't_destination_place_query', schema='assets')
    op.drop_column('trips', 't_distance', schema='assets')
    op.drop_column('trips', 't_duration', schema='assets')
    op.drop_column('trips', 't_directionsResponse', schema='assets')
    # ### end Alembic commands ###
