"""add new column

Revision ID: a4d3125df596
Revises: b8771a84dbea
Create Date: 2025-06-25 20:22:51.041025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4d3125df596'
down_revision = 'b8771a84dbea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema='users') as batch_op:
        batch_op.add_column(sa.Column('org_lang', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema='users') as batch_op:
        batch_op.drop_column('org_lang')

    # ### end Alembic commands ###
