"""t_carbon_emission

Revision ID: a67d549d0a6f
Revises: 4f649d01ccd9
Create Date: 2025-08-06 00:40:48.343415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a67d549d0a6f'
down_revision = '4f649d01ccd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema='assets') as batch_op:
        batch_op.add_column(sa.Column('t_carbon_emission', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema='assets') as batch_op:
        batch_op.drop_column('t_carbon_emission')

    # ### end Alembic commands ###
