"""modify odometer readings

Revision ID: a6d85bee0095
Revises: e27d76b9b73a
Create Date: 2025-03-10 00:34:33.073718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6d85bee0095'
down_revision = 'e27d76b9b73a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('odometer_readings', schema='assets') as batch_op:
        batch_op.add_column(sa.Column('or_description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('odometer_readings', schema='assets') as batch_op:
        batch_op.drop_column('or_description')

    # ### end Alembic commands ###
