"""modify trip

Revision ID: abf481a4ccf8
Revises: ae57231e1ed1
Create Date: 2025-03-29 19:56:34.429774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abf481a4ccf8'
down_revision = 'ae57231e1ed1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema='assets') as batch_op:
        batch_op.add_column(sa.Column('t_started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('t_completed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema='assets') as batch_op:
        batch_op.drop_column('t_completed_at')
        batch_op.drop_column('t_started_at')

    # ### end Alembic commands ###
