"""modify org

Revision ID: ae57231e1ed1
Revises: 2863468f1124
Create Date: 2025-03-17 04:30:44.583540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae57231e1ed1'
down_revision = '2863468f1124'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema='users') as batch_op:
        batch_op.add_column(sa.Column('org_currency', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('org_diesel_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('org_petrol_price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema='users') as batch_op:
        batch_op.drop_column('org_petrol_price')
        batch_op.drop_column('org_diesel_price')
        batch_op.drop_column('org_currency')

    # ### end Alembic commands ###
