"""empty message

Revision ID: b3102aa06c90
Revises: 0b6314aa28d8
Create Date: 2025-08-25 18:59:53.447948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3102aa06c90'
down_revision = '0b6314aa28d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('recipient_email', sa.String(length=200), nullable=True),
    sa.Column('recipient_user_id', sa.String(), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('emailed', sa.Boolean(), nullable=False),
    sa.Column('smsed', sa.Boolean(), nullable=False),
    sa.Column('emailed_date', sa.DateTime(), nullable=True),
    sa.Column('smsed_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.users.id'], ),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='users'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications', schema='users')
    # ### end Alembic commands ###
