"""add read status to notification

Revision ID: b51fed65570f
Revises: b3102aa06c90
Create Date: 2025-08-30 18:12:20.854181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b51fed65570f'
down_revision = 'b3102aa06c90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema='users') as batch_op:
        batch_op.add_column(sa.Column('read', sa.Boolean(), default=False, nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema='users') as batch_op:
        batch_op.drop_column('read')

    # ### end Alembic commands ###
