"""update maintenance model

Revision ID: b8771a84dbea
Revises: 92d80725cb2f
Create Date: 2025-06-16 18:16:36.906139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8771a84dbea'
down_revision = '92d80725cb2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance', schema='assets') as batch_op:
        batch_op.add_column(sa.Column('m_estimated_cost', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('m_attachment', sa.String(), nullable=True))
        batch_op.alter_column('m_organisation_id',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance', schema='assets') as batch_op:
        batch_op.alter_column('m_organisation_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('m_attachment')
        batch_op.drop_column('m_estimated_cost')

    # ### end Alembic commands ###
