"""add f_estimated_litres

Revision ID: bea110179248
Revises: d93da2d39838
Create Date: 2025-08-12 15:05:17.224431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bea110179248'
down_revision = 'd93da2d39838'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuel_request', schema='assets') as batch_op:
        batch_op.add_column(sa.Column('f_estimated_litres', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('f_estimated_cost', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuel_request', schema='assets') as batch_op:
        batch_op.drop_column('f_estimated_cost')
        batch_op.drop_column('f_estimated_litres')

    # ### end Alembic commands ###
