"""adjust timefield in operators

Revision ID: c0b693a38e81
Revises: 97a2ec218032
Create Date: 2024-07-18 01:12:01.728649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0b693a38e81'
down_revision = '97a2ec218032'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema='assets') as batch_op:
        batch_op.alter_column('t_created_at',
                                existing_type=sa.DateTime(),
                                server_default=sa.text('now()'),
                                nullable=False)
        batch_op.alter_column('t_start_elavation',
                              existing_type=sa.Numeric(),
                              nullable=True)
        batch_op.alter_column('t_end_elavation',
                              existing_type=sa.Numeric(),
                              nullable=True)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trips', schema='assets')
    # ### end Alembic commands ###
