"""add fuel model

Revision ID: c4b8ad49e792
Revises: 3032ddb3eb2d
Create Date: 2024-07-27 23:11:07.996969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4b8ad49e792'
down_revision = '3032ddb3eb2d'
branch_labels = None
depends_on = None

def upgrade():
    return 0

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trips', schema='assets')
    op.drop_table('operators', schema='assets')
    op.drop_table('assets', schema='assets')
    op.drop_table('users', schema='users')
    op.drop_table('organization', schema='users')
    op.drop_table('tstatus', schema='assets')
    op.drop_table('status', schema='assets')
    op.drop_table('ostatus', schema='assets')
    # ### end Alembic commands ###
