"""update fuel_request

Revision ID: ca92a29b8d0f
Revises: 808d4962c84f
Create Date: 2025-02-25 23:58:08.152976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca92a29b8d0f'
down_revision = '808d4962c84f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuel_request', schema='assets') as batch_op:
        batch_op.alter_column('f_distance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuel_request', schema='assets') as batch_op:
        batch_op.alter_column('f_distance',
               existing_type=sa.String(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)

    # ### end Alembic commands ###
