"""add org_phone column

Revision ID: cf19d665eed1
Revises: a4d3125df596
Create Date: 2025-06-26 12:20:39.105715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf19d665eed1'
down_revision = 'a4d3125df596'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema='users') as batch_op:
        batch_op.add_column(sa.Column('org_phone', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema='users') as batch_op:
        batch_op.drop_column('org_phone')

    # ### end Alembic commands ###
