"""drop foreign key

Revision ID: d17b3acaff29
Revises: cf19d665eed1
Create Date: 2025-07-01 09:10:03.739645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd17b3acaff29'
down_revision = 'cf19d665eed1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema='users') as batch_op:
        batch_op.drop_constraint('organization_org_created_by_fkey', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organization', schema='users') as batch_op:
        batch_op.create_foreign_key('organization_org_created_by_fkey', 'users', ['org_created_by'], ['id'], referent_schema='users')

    # ### end Alembic commands ###
