"""adjust organization fields

Revision ID: d24e60cb7035
Revises: 2b615a2bc62b
Create Date: 2024-07-16 11:31:40.302092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd24e60cb7035'
down_revision = '2b615a2bc62b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP TABLE users.organization CASCADE')
    op.create_table('organization',
    sa.Column('id', sa.String(), nullable=True),
    sa.Column('default_id', sa.Integer(), nullable=False),
    sa.Column('f_name', sa.String(length=80), nullable=False),
    sa.Column('f_industry', sa.String(length=80), nullable=True),
    sa.Column('f_country', sa.String(length=80), nullable=True),
    sa.Column('f_email', sa.String(length=120), nullable=True),
    sa.Column('f_size', sa.Integer(), nullable=True),
    sa.Column('f_fiscal_start', sa.Date(), nullable=True),
    sa.Column('f_fiscal_stop', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('default_id'),
    sa.UniqueConstraint('f_name'),
    sa.UniqueConstraint('id'),
    schema='users'
    )
    ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organization', schema='users')
    # ### end Alembic commands ###
