"""create firm model

Revision ID: d3a676d1cb13
Revises: 725bec6b6ea6
Create Date: 2024-07-07 18:02:03.313971

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector


# revision identifiers, used by Alembic.
revision = 'd3a676d1cb13'
down_revision = '725bec6b6ea6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
        # Get the current connection
    bind = op.get_bind()
    inspector = Inspector.from_engine(bind)
    
    if 'firm' not in inspector.get_table_names(schema='users'):                                 
        op.create_table('firm',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('f_name', sa.String(length=80), nullable=False),
        sa.Column('f_industry', sa.String(length=80), nullable=False),
        sa.Column('f_country', sa.String(length=80), nullable=False),
        sa.Column('f_email', sa.String(length=120), nullable=False),
        sa.Column('f_size', sa.Integer(), nullable=False),
        sa.Column('f_fiscal_start', sa.Date(), nullable=True),
        sa.Column('f_fiscal_stop', sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('f_country'),
        sa.UniqueConstraint('f_email'),
        sa.UniqueConstraint('f_industry'),
        sa.UniqueConstraint('f_name'),
        schema='users'
        )
        # Check if the 'user' table exists
    if 'user' not in inspector.get_table_names(schema='users'):
        op.create_table('user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=80), nullable=False),
        sa.Column('email', sa.String(length=120), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
        sa.UniqueConstraint('username'),
        schema='users'
        )
        # Check if the 'asset' table exists
    if 'asset' not in inspector.get_table_names(schema='assets'):
        op.create_table('asset',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('a_name', sa.String(length=100), nullable=False),
        sa.Column('a_make', sa.String(length=100), nullable=False),
        sa.Column('a_model', sa.String(length=100), nullable=False),
        sa.Column('a_year', sa.Integer(), nullable=False),
        sa.Column('a_license_plate', sa.String(length=50), nullable=False),
        sa.Column('a_type', sa.String(length=50), nullable=False),
        sa.Column('a_msrp', sa.Float(), nullable=False),
        sa.Column('a_chasis_no', sa.String(length=100), nullable=False),
        sa.Column('a_engine_size', sa.Float(), nullable=False),
        sa.Column('a_tank_size', sa.Float(), nullable=False),
        sa.Column('a_efficiency_rate', sa.Float(), nullable=False),
        sa.Column('a_fuel_type', sa.String(length=50), nullable=False),
        sa.Column('a_cost', sa.Float(), nullable=False),
        sa.Column('a_value', sa.Float(), nullable=False),
        sa.Column('a_depreciation_rate', sa.Float(), nullable=False),
        sa.Column('a_apreciation_rate', sa.Float(), nullable=False),
        sa.Column('a_accumulated_dep', sa.Float(), nullable=False),
        sa.Column('a_image', sa.String(length=200), nullable=True),
        sa.Column('a_attachment1', sa.String(length=200), nullable=True),
        sa.Column('a_attachment2', sa.String(length=200), nullable=True),
        sa.Column('a_attachment3', sa.String(length=200), nullable=True),
        sa.Column('a_status', sa.String(length=50), nullable=False),
        sa.Column('owner_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['owner_id'], ['users.firm.id'], ),
        sa.PrimaryKeyConstraint('id'),
        schema='assets'
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asset', schema='assets')
    op.drop_table('user', schema='users')
    op.drop_table('firm', schema='users')
    # ### end Alembic commands ###
