"""empty message

Revision ID: d93da2d39838
Revises: a67d549d0a6f
Create Date: 2025-08-06 22:04:51.316498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd93da2d39838'
down_revision = 'a67d549d0a6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema='assets') as batch_op:
        batch_op.add_column(sa.Column('c_is_deleted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema='assets') as batch_op:
        batch_op.drop_column('c_is_deleted')

    # ### end Alembic commands ###
