"""modify odometer readings

Revision ID: e27d76b9b73a
Revises: e9d46d3add57
Create Date: 2025-03-07 18:06:16.697301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e27d76b9b73a'
down_revision = 'e9d46d3add57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('odometer_readings', schema='assets') as batch_op:
        batch_op.alter_column('or_reading',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('odometer_readings', schema='assets') as batch_op:
        batch_op.alter_column('or_reading',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)

    # ### end Alembic commands ###
