"""modify odometer readings

Revision ID: e9d46d3add57
Revises: 605275c00fa4
Create Date: 2025-03-07 17:47:33.304139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9d46d3add57'
down_revision = '605275c00fa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DELETE FROM assets.odometer_readings')

    with op.batch_alter_table(
        'odometer_readings', schema='assets'
    ) as batch_op:
        batch_op.alter_column(
            'or_by_drivers',
            existing_type=sa.BOOLEAN(),
            type_=sa.Float(),
            nullable=True,
            postgresql_using='CASE WHEN or_by_drivers THEN 1 ELSE 0 END::double precision'
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('odometer_readings', schema='assets') as batch_op:
        batch_op.alter_column('or_by_drivers',
               existing_type=sa.Float(),
               type_=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
