"""update user

Revision ID: ef4b371f8de9
Revises: a0996392e8ec
Create Date: 2025-02-21 01:20:19.584641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef4b371f8de9'
down_revision = 'a0996392e8ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema='users') as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema='users') as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('phone')
        batch_op.drop_column('role')

    # ### end Alembic commands ###
