"""add read status not nullable

Revision ID: f808ae0bee65
Revises: b51fed65570f
Create Date: 2025-08-30 18:17:17.096386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f808ae0bee65'
down_revision = 'b51fed65570f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('notifications', schema='users') as batch_op:
        batch_op.alter_column('read',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema='users') as batch_op:
        batch_op.alter_column('read',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
