"""modify trip income model

Revision ID: fdf2ce7cf0ba
Revises: 0e027ea83548
Create Date: 2025-04-18 01:44:14.644442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdf2ce7cf0ba'
down_revision = '0e027ea83548'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_income', schema='assets') as batch_op:
        batch_op.add_column(sa.Column('ti_balance', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ti_payment_method', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('ti_payment_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('ti_payment_status', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('ti_payment_reference', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_income', schema='assets') as batch_op:
        batch_op.drop_column('ti_payment_reference')
        batch_op.drop_column('ti_payment_status')
        batch_op.drop_column('ti_payment_date')
        batch_op.drop_column('ti_payment_method')
        batch_op.drop_column('ti_balance')

    # ### end Alembic commands ###
